# GitHub Sponsors (укажите ваш ник на Гитхабе)
github: [Kamil665]

# Популярные платформы для донатов (просто замените 'vash_nik' на свой логин)
patreon: vash_nik
ko_fi: vash_nik
buy_me_a_coffee: vash_nik

# Если хотите указать прямую ссылку (например, на ЮMoney, Boosty, DonationAlerts или PayPal)
custom: ['https://boosty.to/vash_profil', 'https://yoomoney.ru/to/vash_schet']
